package ua.mycredit.mycredit.internal.analytics

enum class CustomAnalyticEvent {
    CLICK_APPLY_FOR_LOAN,
    CLICK_OK_APPLY_FOR_LOAN,
    CLICK_OK_PROMO_CODE,
    CLICK_GO_TO_PROLONG_LOAN,
    CLICK_OK_ACCEPT_AGREEMENT,
    CLICK_OK_ACCEPT_AGREEMENT_FIRST,
    CLICK_OK_ACCEPT_AGREEMENT_REPEATED
}
